### ISSUE TITLE
IE / Cross-browser support

### ISSUE THREAD

**Issue by RyanReese09** [Swader/diffbot-sp-search#8]
Posting this here so there is a record/log and it can be fixed - http://community.sitepoint.com/t/sitepoint-search/193100/4

This should get all IE10/11 working (IE10 untested, just theory).

**Comment by Swader** [comment]
Doesn't work, but have added the prefixes, just in case it fixes _some_ issues somewhere. They can't harm things, so... still looking for fix for IE10 and IE11 though. The body,html height hack breaks the results page on Chrome.

**Comment by RyanReese09** [comment]
Updated the thread with the full fixes for results / search page.
